rootProject.name = "spring-boot-practice"

include("spring-boot-starter")
include("spring-boot-web")
include("web-server")
include("spring-application-init")
include("spring-test")
include("spring-mvc")
include("spring-hateoas")
include("spring-cors-server")
include("spring-cors-client")
include("spring-boot-jdbc")
include("spring-boot-jpa")
include("spring-boot-redis")
include("spring-boot-mongo")
include("spring-boot-neo4j")
include("spring-boot-security")
include("spring-boot-security-customizing")
include("spring-boot-rest")
include("spring-boot-actuator")
include("spring-boot-monitor")